#!/usr/bin/env python3
from subprocess import Popen
import sys
import time

filename = sys.argv[1]
while True:
    print("\nStarting " + filename)
    p = Popen("/usr/bin/python " + filename, shell=True)
    p.wait()
    time.sleep(10)
